### ISSUE TITLE
How do I specify 2 config.csv files (one for prod and other for non-prod) in CC ui repo

### ISSUE THREAD

**Issue by awartika** [linkedin/cruise-control-ui#12]
I would like to specify 2 different config.csv files and have CC-UI pick up the appropriate config.csv based on some environment variable (prod/qa). How do I do that ?

**Comment by nareshv** [comment]
Since CCFE comes to action only in the web browser, the  trick is to serve the appropriate `config.csv` based on some server side code (depending on which webserver/app framework thats being used `php`, `node.js`,  `apache`, `nginx`, `python-Flask`, `django` etc).

Once choice is to use CNAMEs to have different hostnames for two different environments thats running the same CCFE codebase and Automatically rewrite the `/static/config.csv` request to appropriate `/var/www/html/cruise-control-ui/dist/static/{prod,non-prod}.csv` based on the HOST header in HTTP in the config/code of the app framework

Right now  CCFE bootstrap process doesn't have another step which asks the user to chose an environment first and then load the corresponding configuration.

**Comment by nareshv** [comment]
closing, as an alternative has been provided.
