### ISSUE TITLE
CCFE unable to retrieve final response of long POST operation from CC

### ISSUE THREAD

**Issue by kidkun** [linkedin/cruise-control-ui#19]
Most of the GET/POST endpoints in CC is aync operation and if a calculation does not finish in 10 second,  an in-progress response is returned.  Then CC expects a follow-up request with same URL and with the same cookie or the UUID which is returned in the first in-progress response to get the final result.

Looks like currently CCFE does not follow this assumption and specify neither cookie or UUID in follow up request, which result in user never see final result and get a false impression that CC is stuck. What's worse, in this way CCFE initiate a new operation each time and can potential user up all the session execution thread inside CC.

**Comment by nareshv** [comment]
@kidkun ,

- CCFE expects either a valid 200OK + AsyncResponse or 200OK + Normal Responses
- In case of Async Request, right now we are blocked on the https://github.com/linkedin/cruise-control/issues/585 request which is required for https://github.com/linkedin/cruise-control-ui/issues/1
- Sometimes, CC sends empty responses, https://github.com/linkedin/cruise-control/issues/597 with 200OK, which needs to be fixed as well.

For Async Respones with 200OK, the lifecycle of the `User-Task-Id` needs to be well documented for users to understand its behaviour.

- What happens if a old `User-Task-Id` is sent to CC ?
- What happens if cookie value does not match with `User-Task-Id` ? (Depends on the followed deployment architecture, not in CCFE domain.)
- Just by looking at the `User-Task-Id`, should the user make another follow-up call without parsing the response body (normal Body vs Async Body) ?

Lets come up with detailed docs on how do we want to handle these transitions to have good user experience.

Your point about `DOS`ing CC is very much valid and i have brought this up during our internal discussions as well. (This happens without CCFE in place). Lets try to address these one at a time.

First, i'd request you to help unblock with the above 2 tickets i have quoted. This helps many users who are setting up CORS in their environment and also once i push the #1 ticket, they will have good experience.

CC: @efeg

**Comment by kidkun** [comment]
Hey @nareshv Thanks for the detailed response.
For the first blocker you mentioned, [linkedin/cruise-control#585](https://github.com/linkedin/cruise-control/issues/585), we thought you are working on the fix as you mentioned in [PR-418](https://github.com/linkedin/cruise-control/pull/418)  you " will submit another patch which will restrict the usage of exposing CORS headers". Looks like it is the same thing as you brought up in 585.

**Comment by nareshv** [comment]
@kidkun , yes. But the codebase has gone through several refactors in CC from when i have started working on it. The actual ask is to see how to expose the `KafkaCruiseControlConfig` as part of sending responses to the browser. I am not getting enough cycles to look at the new code structure. So, i'd request you to spend some time making this happen.

**Comment by nareshv** [comment]
Now we have the support for the Custom headers in CC responses. This will be taken care of as part of v0.3.0 release of CCFE

**Comment by nareshv** [comment]
added #24, to help user understand when this header is missing from the CC response.

**Comment by nareshv** [comment]
Added a manual control, in case user wishes to refresh the current page. This works along with the above #24 feature.
<img width="1629" alt="manual-refresh" src="https://user-images.githubusercontent.com/1161803/58681429-fb37b100-8389-11e9-819f-e8fada448c15.png">

**Comment by nareshv** [comment]
user task id headers are used in ccfe, code is in v0.3.0 now
